name = "overlearn-registry"
main = "src/index.ts"
compatibility_date = "2025-01-01"
workers_dev = true
routes = [
  { pattern = "overlearn.org/*", zone_id = "c2a83a212bedc0d98f6815e4650ba431" }
]

[vars]
GITHUB_CLIENT_ID = "TODO_CREATE_GITHUB_OAUTH_APP_CLIENT_ID"
GITHUB_API_BASE = "https://api.github.com"

[[r2_buckets]]
binding = "COURSES"
bucket_name = "overlearn-courses"
preview_bucket_name = "overlearn-courses-preview"

[[kv_namespaces]]
binding = "META"
id = "00000000000000000000000000000000"
preview_id = "00000000000000000000000000000000"
