import { readdir, stat } from "node:fs/promises";
import { join, relative, extname } from "node:path";
import { $ } from "bun";

/**
 * Generates src/daemon/spa-assets.gen.ts (gitignored) so the compiled sidecar
 * can serve the built SPA from ui/dist without filesystem access.
 *
 *   --ensure   write an empty stub manifest if the file doesn't exist yet
 *              (keeps typecheck/tests working without a UI build)
 *   --build    install ui deps if needed, run the Vite build, embed ui/dist
 */

const root = join(import.meta.dir, "..");
const uiDir = join(root, "ui");
const distDir = join(uiDir, "dist");
const genPath = join(root, "src", "daemon", "spa-assets.gen.ts");

const header =
  "// GENERATED by scripts/embed-ui-assets.ts — do not edit (gitignored).\n" +
  "// Empty manifest = SPA not built; the daemon falls back to the legacy renderer.\n" +
  "export const uiAssets: Record<string, { base64: string; type: string }> = ";

const contentTypes: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".woff2": "font/woff2",
  ".woff": "font/woff",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".map": "application/json",
  ".json": "application/json",
  ".txt": "text/plain; charset=utf-8",
};

const fail = (message: string): never => {
  console.error(message);
  process.exit(1);
};

const walk = async (dir: string): Promise<string[]> => {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const path = join(dir, entry.name);
      return entry.isDirectory() ? walk(path) : [path];
    }),
  );
  return files.flat();
};

const mode = process.argv[2];

if (mode === "--ensure") {
  if (!(await Bun.file(genPath).exists())) {
    await Bun.write(genPath, `${header}{};\n`);
    console.log(`Wrote stub ${relative(root, genPath)}`);
  }
  process.exit(0);
}

if (mode !== "--build") {
  fail("Usage: bun scripts/embed-ui-assets.ts --ensure | --build");
}

try {
  await stat(join(uiDir, "node_modules"));
} catch {
  await $`bun install --frozen-lockfile`.cwd(uiDir);
}

await $`bun run build`.cwd(uiDir);

const files = await walk(distDir);
const entries: string[] = [];

for (const path of files.sort()) {
  const route = `/${relative(distDir, path).split("\\").join("/")}`;
  const type = contentTypes[extname(path)] ?? "application/octet-stream";
  const base64 = Buffer.from(await Bun.file(path).arrayBuffer()).toString(
    "base64",
  );
  entries.push(
    `  ${JSON.stringify(route)}: { base64: ${JSON.stringify(base64)}, type: ${JSON.stringify(type)} },`,
  );
}

await Bun.write(genPath, `${header}{\n${entries.join("\n")}\n};\n`);
console.log(
  `Embedded ${files.length} SPA assets into ${relative(root, genPath)}`,
);
